# Generated by Django 5.0.2 on 2024-02-24 22:32

from django.db import migrations


def cria_culturas(apps, schema_editor):
    Cultura = apps.get_model("core", "Cultura")
    culturas = ["Soja", "Milho", "Algodão", "Café", "Cana de Açúcar"]
    for nome_cultura in culturas:
        Cultura.objects.get_or_create(nome=nome_cultura)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_fazenda_culturas_plantadas"),
    ]

    operations = [
        migrations.RunPython(cria_culturas),
    ]
