# Generated by Django 5.0.2 on 2024-02-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cria_culturas_iniciais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='sigla',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
