# Generated by Django 5.0.2 on 2024-02-25 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_estado_sigla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fazenda',
            name='estado',
        ),
    ]
